src/Entity/SnsInfo.php
<?php

namespace App\Entity;

use App\Enum\SnsInfoTypeEnum;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SnsInfoRepository::class)
 */
class SnsInfo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="snsInfos")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $user;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private string $type;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private ?string $content;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUrl(): ?string
    {
        return SnsInfoTypeEnum::getLabel($this->type) . $this->content;
    }
}

src/Controller/Profile/ProfileController.php
<?php

declare(strict_types=1);

namespace App\Controller\Profile;

use App\Entity\SnsInfo;
use App\Entity\User;
use App\Enum\SituationEnum;
use App\Form\ProfileFormType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile/{userId}", name="profile_member", requirements={"userId"="\d+"})
     * @Route("/profile", name="profile")
     */
    public function show(UserRepository $userRepo, int $userId = null): Response
    {
        if (false === is_null($userId)) {
            $user = $userRepo->find($userId);
            if (!$user instanceof User) {
                throw new NotFoundHttpException();
            }
        } else {
            $user = $this->getUser();
        }

        $allStatus = $this->isGranted('ROLE_ADMIN') || $user === $this->getUser();

        return $this->render('profile/show.html.twig', [
            'user' => $user,
            'userPosts' => $allStatus ? $user->getPosts() : $user->getPublicPosts(),
            'userComments' => $allStatus ? $user->getComments() : $user->getPublicComments(),
            'extra' => [
                'currentSituation' => SituationEnum::getLabel($user->getCurrentSituation())
            ]
        ]);
    }

    /**
     * @Route("/profile/edit", name="profile_edit")
     */
    public function edit(Request $request, EntityManagerInterface $em): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        if (true === $user->getSnsInfos()->isEmpty()) {
            $snsInfo = new SnsInfo();
            $user->addSnsInfo($snsInfo);
        }

        $form = $this->createForm(ProfileFormType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('profile');
        }

        return $this->render('profile/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/Profile/ProfileEducationController.php
<?php

namespace App\Controller\Profile;

use App\Entity\User;
use App\Entity\UserEducation;
use App\Enum\OpenCountryEnum;
use App\Form\UserEducationType;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Exception\ForbiddenActionException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Intl\Countries;
use Symfony\Component\Routing\Annotation\Route;

class ProfileEducationController extends AbstractController
{
    /**
     * @Route("/profile/educations", name="profile_educations_manage")
     */
    public function index(): Response
    {
        $educations = $this->getUser()->getEducations();
        return $this->render('profile/educations_list.html.twig', [
            'educations' => $educations,
        ]);
    }

    /**
     * @Route("/profile/educations/new", name="profile_educations_new")
     */
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        if (false === $user->isVerified()) {
            return $this->redirectToRoute('profile');
        }

        if ($request->query->has('country')) {
            $education = new UserEducation();
            $education->setUser($user);
            $form = $this->createForm(UserEducationType::class, $education, [
                'country' => $request->query->get('country'),
                'force_custom' => $request->query->has('custom'),
            ]);

            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $em->persist($education);
                $em->flush();
                return $this->redirectToRoute('profile_educations_manage');
            }

            return $this->render('profile/educations_form.html.twig', [
                'education' => $education,
                'country' => $request->query->get('country'),
                'form' => $form->createView(),
            ]);
        }

        return $this->render('profile/educations_form.html.twig', [
            'europeanCountries' => OpenCountryEnum::getOptions(),
            'otherCountries' => array_diff_key(Countries::getNames(), OpenCountryEnum::getOptions()),
        ]);
    }

    /**
     * @Route("/profile/educations/{id}/edit", name="profile_educations_edit")
     */
    public function edit(UserEducation $education, Request $request, EntityManagerInterface $em): Response
    {
        if ($education->getUser() !== $this->getUser()) {
            $this->addFlash('error', 'Something wrong happened');
            return $this->redirectToRoute('profile_educations_manage');
        }

        $form = $this->createForm(UserEducationType::class, $education);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('profile_educations_manage');
        }

        return $this->render('profile/educations_form.html.twig', [
            'education' => $education,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/profile/educations/{id}/delete", name="profile_educations_delete", requirements={"id"="\d+"}))
     */
    public function delete(UserEducation $education, EntityManagerInterface $em): Response
    {
        if ($education->getUser() === $this->getUser()) {
            $em->remove($education);
            $em->flush();
            $this->addFlash('success', 'Entry has been deleted');
        } else {
            $this->addFlash('error', 'Something wrong happened');
        }

        return $this->redirectToRoute('profile_educations_manage');
    }
}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	:: Profile
{% endblock %}

{% block stylesheets %}
	{{ encore_entry_link_tags('profile') }}
{% endblock %}

{% block javascripts %}
	{{ encore_entry_script_tags('profile') }}
{% endblock %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% import _self as formMacros %}

{% macro printSnsSubForm(sns) %}
	<div class="row sns-item">
		<div class="input-group mt-2">
			{{ form_widget(sns.type) }}
			{{ form_widget(sns.content) }}
			<button class="btn btn-outline-danger delete-item-link pull-right">
				<i class="bi bi-trash"></i>
			</button>
		</div>
	</div>
{% endmacro %}

{% block content %}
	<div class="mt-5 mb-4 px-2 px-md-0">
		<h1>Edit profile</h1>

		{{ form_start(form) }}
		{{ form_errors(form) }}

		{{ form_row(form.firstname) }}
		{{ form_row(form.lastname) }}
		{{ form_row(form.birthdate) }}
		{{ form_row(form.gender) }}
		{{ form_row(form.homeCountries) }}
		{{ form_row(form.languages) }}
		{{ form_row(form.currentSituation) }}
		<div style="width:50%">{{ form_row(form.imageFile,{ 'label': 'Profil picture' }) }}</div>


		{{ form_label(form.snsInfos) }}
		<ul class="snsInfos" data-index="{{ form.snsInfos|length > 0 ? form.snsInfos|last.vars.name + 1 : 0 }}" data-prototype="{{ formMacros.printSnsSubForm(form.snsInfos.vars.prototype)|e('html_attr') }}">
			{% for sns in form.snsInfos %}
				{{ formMacros.printSnsSubForm(sns) }}
			{% endfor %}
			<a href="#" class="add-item-link" data-collection-holder-class="snsInfos">add a line</a>
		</ul>

		<button type="submit" class="px-5 mt-4 btn btn-primary">Save</button>
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/profile/educations_form.html.twig
{% extends 'base.html.twig' %}

{% block title %} :: Profile{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('profile') }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('profile') }}
{% endblock %}

{% if form is defined %}{% form_theme form 'bootstrap_5_layout.html.twig' %}{% endif %}

{% block content %}
    <div class="mt-5 mb-5 px-2 px-md-0">
        <h1>Manage schools</h1>

        <div class="my-3">
            <a href="{{ path('profile_educations_manage') }}">Cancel and return to the list</a>
        </div>

        {% if education is defined %}
            {{ form_start(form) }}

            <div class="row">
                {% if form.country is defined %}
                    <div class="col-6">
                        {{ form_row(form.country) }}
                    </div>
                    <div class="col" style="display: block; padding-top: 38px;">
                        <a href="{{ path('profile_educations_new') }}">Change</a>
                    </div>
                {% else %}
                    <div class="col-12">
                        <h3>
                            {{ education.country|country_name }}
                            {% if education.institution is not null %}
                                > {{ education.institution.city.name }} > {{ education.institution.name }}
                            {% endif %}
                        </h3>
                    </div>
                {% endif %}
            </div>
            {% if form.institution is defined %}
                <div class="row">
                    <div class="col-8">{{ form_row(form.institution) }}</div>
                    <div class="col" style="display: block; padding-top: 35px;">
                        <a href="{{ path('profile_educations_new', {'country': country, 'custom': true}) }}">
                            I can't find my institution
                        </a>
                    </div>
                </div>
            {% elseif form.location is defined %}
                <div class="row">
                    <div class="col-4">{{ form_row(form.location) }}</div>
                    <div class="col-8">{{ form_row(form.name) }}</div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col">{{ form_row(form.startDateYear) }}</div>
                <div class="col">{{ form_row(form.startDateMonth) }}</div>
            </div>
            <div class="row">
                <div class="col">{{ form_row(form.endDateYear) }}</div>
                <div class="col">{{ form_row(form.endDateMonth) }}</div>
            </div>
            <div class="row">
                <div class="col">{{ form_row(form.local) }}</div>
            </div>
            <div class="text-center">
                <button type="submit" class="px-5 mt-4 btn btn-primary">Save</button>
            </div>

            {{ form_end(form) }}
        {% else %}
            <form action="" method="GET">
                <label for="country_selection" class="required">Country</label>
                <select id="country_selection" name="country">
                    {% for k, c in europeanCountries %}
                        <option value="{{ k }}">{{ c }}</option>
                    {% endfor %}
                        <option disabled="disabled">-------------------</option>
                    {% for k, c in otherCountries %}
                        <option value="{{ k }}">{{ c }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="px-5 mt-4 btn btn-primary">Next</button>
            </form>
        {% endif %}


    </div>
{% endblock %}

templates/profile/educations_list.html.twig
{% extends 'base.html.twig' %}

{% block title %} :: Profile{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('profile') }}
{% endblock %}

{% block content %}
    <div class="mt-5 mb-4 px-2 px-md-0">
        <h1>Manage schools</h1>

        <div class="my-3">
            <a href="{{ path('profile') }}">Return to the profile</a>
        </div>

        {% for message in app.flashes('success') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        <table class="table">
            <tr>
                <th>Start &#8595;</th>
                <th>End</th>
                <th>Location</th>
                <th>School name</th>
                <th>As a local</th>
                <th>Actions</th>
            </tr>
            {% for s in educations %}
                <tr>
                    <td>{{ s.startDate|date('M Y') }}</td>
                    <td>{{ s.endDate|date('M Y') }}</td>
                    {% if s.institution is not null %}
                        <td>{{ s.institution.city }}, {{ s.institution.city.country|country_name }}</td>
                        <td>{{ s.institution.name }}</td>
                    {% else %}
                        <td>{{ s.location }}, {{ s.country|country_name }}</td>
                        <td>{{ s.name }}</td>
                    {% endif %}
                    <td>{{ s.local ? 'yes' : 'Mobility' }}</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="{{ path('profile_educations_edit', {id: s.id}) }}" class="btn btn-sm btn-secondary">
                                <i class="bi bi-pencil-fill"></i>Edit
                            </a>
                            <a href="{{ path('profile_educations_delete', {id: s.id}) }}" class="btn btn-sm btn-danger">
                                <i class="bi bi-trash3-fill"></i>Delete
                            </a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href="{{ path('profile_educations_new') }}" class="btn btn-sm btn-primary text-white">
            <i class="bi bi-plus-circle-fill"></i> Add a education to the list
        </a>
    </div>
{% endblock %}

templates/profile/posts.html.twig
{% extends 'base.html.twig' %}

{% block title %} :: Posts{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('profile') }}
{% endblock %}

{% block content %}
    <div class="my-5 text-center">
        <h1>{% for tag in tags %}#{{ tag }} {% endfor %}</h1>
        <div class="nb-results">{{ posts|length }} result(s)</div>
        <div class="posts-list">
            {% for post in posts %}
                {% include '_post.html.twig' with {'post': post, 'multi': true} only %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	:: Profile
{% endblock %}

{% block stylesheets %}
	{{ encore_entry_link_tags('profile') }}
{% endblock %}

{% block javascripts %}
	{{ encore_entry_script_tags('profile') }}
{% endblock %}

{% block content %}
	<div class="profile-content my-md-4">
		{% for message in app.flashes('success') %}
			<div class="alert alert-success">{{ message }}</div>
		{% endfor %}
		<div class="row pt-3 pt-md-5 pb-4 compass-pattern">
			{%
                if false == is_granted('ROLE_ADMIN') and
                    (
                        false == user.isVerified
                        or (user.snsInfos|length < 1 and user.languages|length < 1)
                        or user.educations|length < 1
                        or user.posts|length < 1
                    )
            %}
				<div class="first-steps">
					<div class="title">Welcome to Compass platform!</div>
					<ul class="list-unstyled">
						<li class="{{ true == user.isVerified ? 'checked' }}">
							<i class="bi bi-check2-circle"></i>
							Verify your email address with the link you received by mail
						</li>
						<li class="{{ user.snsInfos|length > 0 or user.languages|length > 0 ? 'checked' }}">
							<i class="bi bi-check2-circle"></i>
							Fill in
							<a href="{{ path('profile_edit') }}">your profile</a>
							with information about you :
							                            languages you speak, how to reach you (instagram, etc...)
						</li>
						<li class="{{ user.educations|length > 0 ? 'checked' }}">
							<i class="bi bi-check2-circle"></i>
							Tell us the
							<a href="{{ path('profile_educations_manage') }}">mobility and the schools</a>
							you have been to in your profile.
						</li>
						<li class="{{ user.posts|length > 0 ? 'checked' }}">
							<i class="bi bi-check2-circle"></i>
							Create
							<a href="{{ path('post_ideas') }}">your first post</a>
							for tips, feedback, or
							                            anything to share with people who want to go in a mobility!
						</li>
					</ul>
				</div>
			{% endif %}
			<div class="col-12 col-md-6 mb-4 text-center">
				<h1>
					{% for r in user.roles %}
						{% if r == 'ROLE_ADMIN' %}
							<i class="bi bi-asterisk text-secondary" title="Administrator"></i>
						{% endif %}
					{% endfor %}
					{{ user.firstname }}
					{% if user.imageName is not null %}
						<img src="{{ asset('/images/users/'~ user.imageName) }}" style="width:25%" class="" alt="...">

					{% else %}
						<i class="bi bi-person-fill" style="font-size:5rem; color:#ffb255"></i>
					{% endif %}
					{% if user.gender in [0,1] %}
						<i class="bi bi-gender-{{ user.gender == 0 ? 'female' : 'male' }}"></i>
					{% endif %}

				</h1>
				{% if app.user == user %}
					{% if false == user.isVerified %}
						<i>
							Please confirm your email address (by clicking the link you received in your mail)
							                            before using your account.
						</i>
					{% else %}
						<a href="{{ path('profile_edit') }}" class="btn btn-sm btn-secondary">
							<i class="bi bi-pencil-square"></i>
							Edit profile
						</a>
						<a href="{{ path('profile_educations_manage') }}" class="btn btn-sm btn-secondary">
							<i class="bi bi-mortarboard"></i>
							Manage educations
						</a>
						<div class="call-to-action">
							<a href="{{ path('post_ideas') }}" class="btn btn-primary">
								Share your experience, create posts !
							</a>
						</div>
					{% endif %}
				{% endif %}
				<div class="social-networks mt-md-3">
					{% for sns in user.snsInfos %}
						<a href="{{ sns.url }}" title="{{ sns.url }}" target="_blank">
							<i class="bi bi-{{ sns.type }}"></i>
							{{ sns.type }}
						</a><br>
					{% endfor %}
				</div>
			</div>
			<div class="col-12 col-md-6 col-6">
				<ul class="identity-card mx-3 ms-md-0 me-md-5 list-unstyled">
					<li>
						<strong>age:</strong>
						<span title="{{ user.birthdate|date('Y-m-d') }}">{{ user.age }}</span>
					</li>
					<li>
						{% if user.homeCountries|length == 0 %}
							<strong>home country:</strong>
							<i>undefined</i>
						{% else %}
							<strong>{{ user.homeCountries|length > 1 ? 'home countries' : 'home country'}}:</strong>
							{% for n in user.homeCountries %}
								{{ n|country_name }}{{ loop.revindex > 1 ? ', ' }}
							{% endfor %}
						{% endif %}
					</li>
					<li>
						{% if user.languages|length == 0 %}
							<strong>language:</strong>
							<i>undefined</i>
						{% else %}
							<strong>language{{ user.languages|length > 1 ? 's'}}:</strong>
							{% for l in user.languages %}
								{{ l|language_name }}{{ loop.revindex > 1 ? ', ' }}
							{% endfor %}
						{% endif %}
					</li>
					{% if extra.currentSituation is not empty %}
						<li>
							<strong>current situation:</strong>
							{{ extra.currentSituation }}
						</li>
					{% endif %}

					{% set originSchools = user.educations|filter(v => v.local == true) %}
					{% set mobilitySchools = user.educations|filter(v => v.local == false) %}

					{% if originSchools|length > 0 or app.user == user %}
						<li class="pt-3">
							<strong>I was a local student in:</strong>
							<ul>
								{% for s in originSchools %}
									<li>
										{% if s.institution is not null %}
											{{ s.institution.name }}
											<i>({{ s.institution.city.name }},
												{{ s.institution.city.country|country_name }})</i>
										{% else %}
											{{ s.name }}
											<i>({{ s.location }},
												{{ s.country|country_name }})</i>
										{% endif %}
										<br><small>{{ s.startDate|date('M Y') }}
											-
											{{ s.endDate|date('M Y') }}</small>
									</li>
								{% endfor %}
							</ul>
						</li>
					{% endif %}
					{% if mobilitySchools|length > 0 or app.user == user %}
						<li class="pt-3">
							<strong>I was an exchange student in:</strong>
							<ul>
								{% for s in mobilitySchools %}
									<li>
										{% if s.institution is not null %}
											{{ s.institution.name }}
											<i>({{ s.institution.city.name }},
												{{ s.institution.city.country|country_name }})</i>
										{% else %}
											{{ s.name }}
											<i>({{ s.location }},
												{{ s.country|country_name }})</i>
										{% endif %}
										<br><small>{{ s.startDate|date('M Y') }}
											-
											{{ s.endDate|date('M Y') }}</small>
									</li>
								{% endfor %}
							</ul>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
		<div class="profile-stat py-3 px-5 row">
			<div class="col py-md-4">
				<div class="profile-stat-badge">
					<div>
						<i class="bi bi-chat-left-text"></i>
					</div>
					<div>
						<strong>{{ userPosts|length < 10 ? '0' }}{{ userPosts|length }}</strong>
						<br>posts
					</div>
				</div>
			</div>
			<div class="col py-md-4">
				<div class="profile-stat-badge">
					<div>
						<i class="bi bi-chat-quote"></i>
					</div>
					<div>
						<strong>{{ userComments|length < 10 ? '0' }}{{ userComments|length }}</strong><br>comments</div>
				</div>
			</div>
			<div class="col py-md-4">
				<div class="profile-stat-badge">
					<div>
						<i class="bi bi-hand-thumbs-up"></i>
					</div>
					<div>
						<strong>{{ user.reactions|length < 10 ? '0' }}{{ user.reactions|length }}</strong><br>reactions</div>
				</div>
			</div>
		</div>
		{% if userPosts|length > 0 %}
			<div class="text-center pt-4 pb-2 py-md-5 compass-pattern">
				<h2>Posts</h2>
				<div class="posts-list">
					{% for post in userPosts %}
						{% include '_post.html.twig' with {'post': post, 'profile': true} only %}
					{% endfor %}
				</div>
			</div>
		{% endif %}
	</div>
{% endblock %}