src/Entity/Post.php
<?php

namespace App\Entity;

use App\Enum\PostTypeEnum;
use App\Repository\PostRepository;
use App\Validator as CustomAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @CustomAssert\ContainsTopic
 */
class Post
{
    use ModerableTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private User $author;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private string $type = PostTypeEnum::POST;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $title;

    /**
     * @ORM\Column(type="text")
     */
    private ?string $content;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="posts")
     * @Assert\Count(min=1, minMessage="A post should have at least one tag.")
     */
    private Collection $tags;

    /**
     * @ORM\ManyToOne(targetEntity=Institution::class, inversedBy="posts")
     */
    private ?Institution $institution = null;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="posts")
     */
    private ?City $city = null;

    /**
     * @ORM\Column(type="string", length=2, nullable=true)
     * @Assert\Choice(callback={"App\Enum\OpenCountryEnum", "getReadableChoices"})
     */
    private ?string $country = null;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private \DateTimeImmutable $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=PostReaction::class, mappedBy="post", orphanRemoval=true)
     */
    private Collection $reactions;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post", orphanRemoval=true)
     */
    private Collection $comments;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
        $this->reactions = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getTopic()
    {
        if ($this->institution) {
            return $this->institution;
        } elseif ($this->city) {
            return $this->city;
        } else {
            return $this->country;
        }
    }

    public function getInstitution(): ?Institution
    {
        return $this->institution;
    }

    public function setInstitution(?Institution $institution): self
    {
        $this->institution = $institution;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|PostReaction[]
     */
    public function getReactions(): Collection
    {
        return $this->reactions;
    }

    public function getReactionOfUser(?User $user): ?PostReaction
    {
        if ($user instanceof User) {
            foreach ($this->reactions as $reaction) {
                if ($reaction->getUser() === $user) {
                    return $reaction;
                }
            }
        }
        return null;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Comment[]
     */
    public function getPublicComments(): array
    {
        return array_filter($this->comments->toArray(), function (Comment $c) {
            return $c->isPublic();
        });
    }

    /**
     * @param User|null $user
     * @return array|Comment[]
     */
    public function getCommentsOfUser(?User $user): array
    {
        $comments = [];
        if ($user instanceof User) {
            foreach ($this->comments as $comment) {
                if ($comment->getAuthor() === $user) {
                    $comments[] = $comment;
                }
            }
        }
        return $comments;
    }

    public function __toString()
    {
        return '#' . $this->id . ' ' . $this->title;
    }
}

templates/_post.html.twig
<div class="post {{ post.moderationStatus }}">
	<div class="icon">
		<i class="bi bi-chat-left-text"></i>
	</div>
	<div class="head">
		<div class="title">
			{% if 'waiting' == post.moderationStatus %}
				<span class="badge bg-warning text-black">Waiting for validation</span>
			{% elseif 'refused' == post.moderationStatus %}
				<span class="badge bg-danger">Refused by moderator</span>
			{% endif %}
			{% if search ?? false %}
				{{ post.title|replace({'¤s¤': '<span class="highlight">', '¤/s¤': '</span>'})|raw }}
			{% else %}
				{{ post.title }}
			{% endif %}
		</div>
		<div class="created-at" title="{{ post.createdAt|date }}">
			{% if (grid ?? false) or (multi ?? false) %}
				by
				<a href="{{ path('profile_member', {'userId': post.author.id}) }}">{{ post.author.firstname }}</a>
				{% if post.author.imageName is not null %}

					<img src="{{ asset('/images/users/'~ post.author.imageName) }}" style="width:15%" class="" alt="picture profile">
					&nbsp;
				{% else %}
					<i class="bi bi-person-fill" style=" font-size: 2rem;color:#ffb255"></i>
				{% endif %}
			{% endif %}
			&nbsp; on
			{{ post.createdAt|date('M d') }}
		</div>
		<div class="tags">
			{% for tag in post.tags %}
				<a href="{{ path('tags_list', {'tags': tag.name}) }}">#{{ tag.name }}</a>
			{% endfor %}
			{% if post.institution is not null %}
				<a href="{{ path('institution_list', {'slug': post.institution.slug}) }}" title="{{ post.institution.city }}, {{ post.institution.city.country|country_name }}">
					<i class="bi bi-geo-alt-fill"></i>
					{{ post.institution.name }}
				</a>
			{% elseif post.city is not null%}
				<a href="{{ path('city_list', {'slug': post.city.slug}) }}" title="{{ post.city.country|country_name }}">
					<i class="bi bi-geo-alt-fill"></i>
					{{ post.city }}
				</a>
			{% elseif post.country is not null %}
				<a href="{{ path('country_list', {'country': post.country}) }}">
					<i class="bi bi-geo-alt-fill"></i>
					{{ post.country|country_name }}
				</a>
				{% endif%}
			</div>
		</div>
		<div class="body">
			{% if grid ?? false %}
				{{ post.content|slice(0, 50) ~ '...'  }}
				<a href="{{ path('post_show', {'id': post.id}) }}">read more</a>
			{% elseif search ?? false %}
				{{ post.content|replace({'¤s¤': '<span class="highlight">', '¤/s¤': '</span>'})|raw }}
			{% else %}
				{{ post.content }}
			{% endif %}
		</div>
		{% if (profile ?? false) and app.user == post.author %}
			<div class="actions mt-3">
				<form action="{{ path('post_delete', {id: post.id}) }}" method="POST" onsubmit="return confirm('Are you sure to delete this post ?')">
					<input type="hidden" name="_method" value="DELETE">
					<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
					<button class="btn btn-sm btn-outline-danger">Delete the post</button>
				</form>
			</div>
		{% else %}
			<div class="row comments-reactions mt-3">
				<div class="col-md comments-info">
					<a href="{{ path('post_show', {'id': post.id}) }}#comments" class="comment-reaction ">
						<i class="on bi bi-chat-quote{{ post.commentsOfUser(app.user) is not empty ? '-fill' }}"></i>
						{% if grid ?? false %}
							{{ post.publicComments|length }}
						{% else %}
							Comments ({{ post.publicComments|length }})
						{% endif %}
					</a>
				</div>
				<div class="col-md reactions text-end">
					{% include '_post_reactions.html.twig' with {'post': post, 'compact': grid ?? false} only %}
				</div>
			</div>
		{% endif %}
	</div>

templates/_post_reactions.html.twig
{% set likeOnOff = post.reactionOfUser(app.user) is not null and post.reactionOfUser(app.user).type == 'like'  %}
{% set loveOnOff = post.reactionOfUser(app.user) is not null and post.reactionOfUser(app.user).type == 'love'  %}
{% set usefulOnOff = post.reactionOfUser(app.user) is not null and post.reactionOfUser(app.user).type == 'useful'  %}
{% set likeCount = post.reactions|filter(r => r.type == 'like')|length %}
{% set loveCount = post.reactions|filter(r => r.type == 'love')|length %}
{% set usefulCount = post.reactions|filter(r => r.type == 'useful')|length %}

{% if compact is not defined or compact == false %}
    <div class="reaction-btn-group">
        <a data-target="{{ path('post_react', {'id': post.id, 'type': (likeOnOff ? 'undo' : 'like')}) }}"
           class="like-reaction {{ likeOnOff ? 'on' : 'off' }}">
            <i class="on bi bi-hand-thumbs-up-fill"></i>
            <i class="off bi bi-hand-thumbs-up"></i>
            Like ({{ likeCount }})
        </a>
        <a data-target="{{ path('post_react', {'id': post.id, 'type': (loveOnOff ? 'undo' : 'love')}) }}"
           class="love-reaction {{ loveOnOff ? 'on' : 'off' }}">
            <i class="on bi bi-heart-fill"></i>
            <i class="off bi bi-heart"></i>
            Love ({{ loveCount }})
        </a>
        <a data-target="{{ path('post_react', {'id': post.id, 'type': (usefulOnOff ? 'undo' : 'useful')}) }}"
           class="useful-reaction {{ usefulOnOff ? 'on' : 'off' }}">
            <i class="on bi bi-check-circle-fill"></i>
            <i class="off bi bi-check-circle"></i>
            Useful ({{ usefulCount }})
        </a>
    </div>
{% else %}
    <div class="compact-reactions">
        {% if likeCount > 0 %}
            <span class="{{ likeOnOff ? 'on' : 'off' }} like-reaction"
                  title="{{ likeCount }} people{{ likeOnOff ? ' (you included)' }} like this post">
                <i class="on bi bi-hand-thumbs-up{{ likeOnOff ? '-fill on' }}"></i>
                {{ post.reactions|filter(r => r.type == 'like')|length }}
            </span>
        {% endif %}
        {% if loveCount > 0 %}
            <span class="{{ loveOnOff ? 'on' : 'off' }} love-reaction"
                  title="{{ loveCount }} people{{ loveOnOff ? ' (you included)' }} love this post">
                <i class="bi bi-heart{{ loveOnOff ? '-fill on' }}"></i>
                {{ loveCount }}
            </span>
        {% endif %}
        {% if usefulCount > 0 %}
            <span class="{{ usefulOnOff ? 'on' : 'off' }} useful-reaction"
                  title="{{ usefulCount }} people{{ usefulOnOff ? ' (you included)' }} think this post is useful">
                <i class="bi bi-check-circle{{ usefulOnOff ? '-fill on' }}"></i>
                {{ usefulCount }}
            </span>
        {% endif %}
    </div>
{% endif %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Compass
			{% block title %}{% endblock %}
		</title>
		<link rel="icon" href="{{ asset('build/images/compass_logo.svg') }}">

		{{ encore_entry_link_tags('app') }}

		{% block stylesheets %}{% endblock %}

		{{ encore_entry_script_tags('app') }}

		{% block javascripts %}{% endblock %}
	</head>
	<body>
		{% if 'staging.' in app.request.getSchemeAndHttpHost() %}
			<div class="staging-banner">
				This is the staging (testing) environment. Content added, edited and deleted here won't affect the
																                public version. The database of this version is regularly emptied.
			</div>
			<div class="my-4 my-sm-2 my-lg-0">&nbsp;</div>
		{% elseif 'demo.' in app.request.getSchemeAndHttpHost() %}
			<div class="demo-banner">
				This is the demo environnement. Content added, edited and deleted here won't affect the
																                public version. The database of this version is regularly emptied.
																                You can try the platform by logging as an
				<span title="admin@admin.com | password">admin</span>
				or any
				<span title="ex: l.humbert@mail.fr | password">user</span>
				in database.
			</div>
			<div class="my-4 my-sm-2 my-lg-0">&nbsp;</div>
		{% endif %}

		{% set path = app.request.attributes.get('_route') %}
		<div class="cover-container d-flex w-100 px-md-3 pt-md-2 mx-auto flex-column">
			<header class="mb-auto px-3 px-md-0">
				<div>
					<div class="float-md-start mb-0 me-2"></div>
					<nav role="navigation" class="navbar navbar-expand-md navbar-light">
						<div class="container-fluid">
							<a href="{{ path('homepage') }}" class="logo">
								<img src="{{ asset('build/images/compass_logo.svg') }}" alt="Compass logo"/>
							</a>
							<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
								<span class="navbar-toggler-icon"></span>
							</button>
							<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
								<ul class="navbar-nav me-auto mb-2 mb-lg-0">
									<li class="nav-item">
										<a class="nav-link {{ path == 'homepage' ? 'active' }}" aria-current="page" href="{{ path('homepage') }}">Home</a>
									</li>
									<li class="nav-item">
										<a class="nav-link {{ path == 'search' ? 'active' }}" href="{{ path('search') }}">
											<i class="bi bi-search"></i>
											Search</a>
									</li>
									<li class="nav-item">
										<a class="nav-link {{ path == 'home_faq' ? 'active' }}" href="{{ path('home_faq') }}">FAQ</a>
									</li>
									<li class="nav-item">
										<a class="nav-link {{ path == 'home_contact_us' ? 'active' }}" href="{{ path('home_contact_us') }}">Contact us</a>
									</li>
								</ul>
								<form class="d-flex">
									{% if app.user is null %}
										<a class="nav-link" href="{{ path('app_login') }}">Log in</a>
										<a class="nav-link btn btn-primary px-4 text-white" href="{{ path('app_register') }}">
											Sign up
										</a>
									{% else %}
										{% if is_granted('ROLE_ADMIN') %}
											<a class="nav-link btn btn-outline-secondary px-3 position-relative" href="{{ path('admin') }}">
												<i class="bi bi-sliders"></i>
												Dashboard
												{% set dash_notifs = notification_service.getUserDashboardNotificationsCount(app.user) %}
												{% if dash_notifs > 0 %}
													<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
														{{ dash_notifs }}
														<span class="visually-hidden">notifications</span>
													</span>
												{% endif %}
											</a>
										{% endif %}
										<a class="nav-link btn btn-outline-primary px-4 {% if is_granted('IS_IMPERSONATOR') %}btn-danger{% endif %}" href="{{ path('profile') }}">
											<i class="bi bi-person-fill"></i>
											{{ app.user.firstname }}
										</a>
										{% if is_granted('IS_IMPERSONATOR') %}
											<a class="nav-link" href="{{ impersonation_exit_path(path('homepage') ) }}">Exit impersonation</a>
										{% else %}
											<a class="nav-link" href="{{ path('app_logout') }}">Log out</a>
										{% endif %}
									{% endif %}
								</form>
							</div>
						</div>
					</nav>
				</div>
			</header>

			{% block content %}{% endblock %}

			<footer class="py-2 py-md-4 text-center">
				<div class="beta-message">
					<i class="bi bi-cone-striped"></i>
					This website is still in beta version. Some functionalities are still limited and we are working
																				                    to improve it.
					<br>Feel free to contact us to report any problem or give us your feedback.
				</div>
				<nav>
					<a class="py-2" href="{{ path('home_terms_and_conditions') }}">Terms and conditions</a>
					•
					<a class="py-2" href="{{ path('home_privacy_policy') }}">Privacy policy</a>
					•
					<a class="py-2" href="{{ path('home_charter') }}">Charter</a>
					•
					<a class="py-2" href="{{ path('home_contact_us') }}">Contact us</a>
				</nav>
				<a href="{{ path('project_presentation') }}">More information about the Compass project</a>
				<p class="mt-2">This project has been funded by the European Union<br/>© 2022 Compass</p>
			</footer>
		</div>
	</body>
</html>

templates/project_base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Compass{% block title %}{% endblock %}</title>
        <link rel="icon" href="{{ asset('build/images/compass_logo.svg') }}">

        {{ encore_entry_link_tags('app') }}

        {% block stylesheets %}
        {% endblock %}

        {{ encore_entry_script_tags('app') }}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body class="bg-secondary compass-white-pattern">

    {% set path = app.request.attributes.get('_route') %}
    <div class="cover-container d-flex w-100 mx-auto flex-column bg-white">
        {% block header %}
            <header class="mb-auto">
                <div>
                    <div class="float-md-start mb-0 me-2">
                    </div>
                    <nav  role="navigation" class="navbar navbar-expand-md navbar-dark bg-secondary pb-3 px-3 px-md-0">
                        <div class="container-fluid">
                            <a href="{{ path('project_presentation') }}" class="logo">
                                <img src="{{ asset('build/images/compass_logo.svg') }}" alt="Compass logo"/>
                            </a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="nav-link {{ path == 'project_presentation' ? 'active' }}" aria-current="page" href="{{ path('project_presentation') }}">Presentation</a>
                                    </li>
{#                                    <li class="nav-item">#}
{#                                        <a class="nav-link {{ path == 'project_news' ? 'active' }}" href="{{ path('project_news') }}">News</a>#}
{#                                    </li>#}
                                    <li class="nav-item">
                                        <a class="nav-link {{ path == 'project_resources' ? 'active' }}" href="{{ path('project_resources') }}">Resources</a>
                                    </li>
                                </ul>
                                <form class="d-flex">
                                    <a class="nav-link btn btn-primary px-4 text-white" href="{{ path('homepage') }}">
                                        <i class="bi bi-arrow-left-circle"></i>
                                        Return on Compass app
                                    </a>
                                </form>
                            </div>
                        </div>
                    </nav>
                </div>
            </header>
        {% endblock %}

        <div class="bg-white px-md-5 pt-md-2">
            {% block content %}{% endblock %}
        </div>

        <footer class="py-2 py-md-4 text-center bg-white">
            <p class="mt-2">This project has been funded by the European Union<br/>© 2022 Compass</p>
        </footer>
    </div>
    </body>
</html>